[tools]
python = "3.13"

[env]
_.python.venv = { path = ".venv", create = true, python = "3.13" }

[tasks.run]
description = "Run the development server"
alias = "r"
run = "fastapi dev main.py"

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "pip install -r requirements.txt"

[tasks.test]
description = "Run pytest"
alias = "t"
run = "pytest"

[tasks.coverage]
description = "Run coverage and fuzzing tests"
alias = "c"
run = "uvx schemathesis run  -c all --exclude-checks positive_data_acceptance http://127.0.0.1:8000/openapi.json"