[tools]
python = "3.13"

[env]
_.python.venv = { path = ".venv", create = true, python = "3.13" }

[tasks.run]
description = "Run the production server"
alias = "r"
run = "fastapi run main.py"

[tasks.dev]
description = "Run the development server"
alias = "d"
run = "fastapi dev main.py"

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "pip install -r requirements.txt"

[tasks.test]
description = "Run pytest"
alias = "t"
run = "pytest"